language: objective-c
osx_image: xcode7.0
before_install:
- gem install xcpretty -N
script:
- set -o pipefail
- xcodebuild -project WhereAmI.xcodeproj -scheme WhereAmI -sdk iphonesimulator  -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild -project "./Example/Where Am I Demo.xcodeproj" -scheme "Where Am I" -sdk iphonesimulator  -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=YES build | xcpretty -c
- pod lib lint --quick
